#!/usr/bin/env bash

set -euo pipefail

input_json="$(cat)"

echo >&2 -n 'Parsing...'
state_bucket="$(jq -r '.source.state_bucket' <<< "${input_json}")"
cluster="$(jq -r '.source.cluster' <<< "${input_json}")"
echo >&2 ' done!'

set +e
kops validate cluster --state "${state_bucket}" --name "${cluster}" >&2
# construct the final output
if [[ $? -eq 0 ]]; then
  jq --raw-input '[{"status": . }]' <<< "true"
else
  jq --raw-input '[{"status": . }]' <<< "false"
  exit 1
fi
set -e
